In [1]:
# How to move from DF to 2-D Numpy

# A Machine Learning frameworks work on numpy, so even more categorical data need to be converted to numeric

# the basic idea is to encode each category to like one hot encoding in pandas it's done with get_dummies function

import pandas as pd
import numpy as np 

In [2]:

# Creating a simple DataFrame
data = {
    'Animal': ['Dog', 'Cat', 'Bird', 'Dog', 'Cat'],
    'Color': ['Black', 'White', 'Black', 'Brown', 'Black'],
    'Age': [3, 2, 1, 5, 2]  # Including a numeric column for variety
}

df = pd.DataFrame(data)

print(df)

  Animal  Color  Age
0    Dog  Black    3
1    Cat  White    2
2   Bird  Black    1
3    Dog  Brown    5
4    Cat  Black    2


In [10]:
df_encoded = pd.get_dummies(df, columns=["Animal","Color"]).astype(int)

print(df_encoded.columns)
print(df_encoded)

Index(['Age', 'Animal_Bird', 'Animal_Cat', 'Animal_Dog', 'Color_Black',
       'Color_Brown', 'Color_White'],
      dtype='object')
   Age  Animal_Bird  Animal_Cat  Animal_Dog  Color_Black  Color_Brown  \
0    3            0           0           1            1            0   
1    2            0           1           0            0            0   
2    1            1           0           0            1            0   
3    5            0           0           1            0            1   
4    2            0           1           0            1            0   

   Color_White  
0            0  
1            1  
2            0  
3            0  
4            0  


In [11]:
# convert to numpy

n_matrix = df.values
print(n_matrix)

[['Dog' 'Black' 3]
 ['Cat' 'White' 2]
 ['Bird' 'Black' 1]
 ['Dog' 'Brown' 5]
 ['Cat' 'Black' 2]]


In [13]:
n_matrix = df_encoded.values
print(n_matrix) # note obviosuly you see so called "curse of dimensionality" :)

[[3 0 0 1 1 0 0]
 [2 0 1 0 0 0 1]
 [1 1 0 0 1 0 0]
 [5 0 0 1 0 1 0]
 [2 0 1 0 1 0 0]]
