In [1]:
# Numpy

In [3]:
import numpy as np 

# Initializing a Numpy array

arr = np.array([-1,2,5], dtype=np.float32)

# print the representation of the array

print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


In [4]:
# Numpy Arrays

# 1. Arrays
# 2. Copying
# 3. Casting 
# 4. NaN
# 5. Infinity


In [5]:
# 2D Matrix

import numpy as np
arr = np.array([[0,1,2],[3,4,5]], dtype = np.float32)
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [6]:
# By default upcast 
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


In [9]:
# Copying 

# by default behavior is reference 
a = np.array([0,1])
b = np.array([9,8])
c = a 
print("Array a: {}".format(repr(a)))
c[0] = 5 
print("Array a: {}".format(repr(a)))

d = b.copy()
d[0] = 6
print("Array b: {}".format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


In [10]:
# Data type casting
arr = np.array([0,1,2])
print(arr.dtype)
arr = arr.astype(np.float128)
print(arr.dtype)

int64
float128


In [12]:
# NaN act as a placeholder for non vale, np.nan is a filler for incomplete data 

arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# ! np.nan is not valid for int data type
#np.array([np.nan, 1, 2], dtype=np.int32)
np.array([np.nan, 1, 2], dtype=np.float32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


array([nan,  1.,  2.], dtype=float32)

In [16]:
# Infinity 

print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in a OverflowError: If we uncomment line 10 and run again.
#np.array([np.inf, 3], dtype=np.int32)
np.array([np.inf, 3], dtype=np.float32)

True
array([inf,  5.])
array([-inf,   1.])


array([inf,  3.], dtype=float32)