In [1]:
# Numpy Basics

# Perform basic operatioms to create and modify Numpy arrays

# 1. Ranged data
# 2. Reshaping data
# 3. Transposing data
# 4. Zeros and ones

In [2]:
#  1. Ranged Data
import numpy as np
# np.arange() -> return 1d array

arr = np.arange(5)

print(repr(arr))

array([0, 1, 2, 3, 4])


In [3]:
arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1,4)
print(repr(arr))

arr = np.arange(-1.5,4,2)
print(repr(arr))

array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [4]:
# To specify number of elements, rather step size, we can use np.linspace start,end,end inclusive by default

arr = np.linspace(5,11, num =4)
print(repr(arr))

arr = np.linspace(5,11,num=4,endpoint=False)
print(repr(arr))

arr = np.linspace(5,11,num=4,dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


In [5]:
# 2. Reshaping data

arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2,4))
print(repr(reshaped_arr))
print("New shape: {}".format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1,2,2))
print(repr(reshaped_arr))
print("New shape: {}".format(reshaped_arr.shape))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


In [6]:
# flatten data
arr = np.arange(8)
arr = np.reshape(arr, (2,4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))



array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


In [8]:
# 3. Transposing the data

# np.transpose // rows become columns
arr = np.arange(8)
arr = np.reshape(arr, (4,2))
transposed = np.transpose(arr)

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


In [19]:
arr = np.arange(24)
arr = np.reshape(arr, (2, 12))
transposed = np.transpose(arr, axes=(1,0))
print('arr shape: {}'.format(arr.shape))
print(repr(arr))
print('transposed shape: {}'.format(transposed.shape))
print(repr(transposed))

arr shape: (2, 12)
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
transposed shape: (12, 2)
array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])


In [20]:
# 4. Zeros and ones

arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2,3))
print(repr(arr))

arr = np.ones((2,3), dtype = np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [21]:
# take a shape of another array

arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)
