In [3]:
# Math

# 1. Arithmetic
# 2. Non-linear functions
# 3. Matrix multiplication

import numpy as np

In [4]:

#1. Arithmetic 
# apply arithmetic to each element with a single operation

arr = np.array([[1,2],[3,4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [6]:
# convert fahrenheit to celsius

def f2c(temps):
    return (5/9)*(temps-32)

fahrenheits = np.array([32,-4,14,-40])
celsius = f2c(fahrenheits)

print("Celcius: {}".format(repr(celsius)))

Celcius: array([  0., -20., -10., -40.])


In [7]:
# 2. Non-linear functions
# exponential and logarithms

arr = np.array([[1,2],[3,4]])

print(repr(np.exp(arr)))

print(repr(np.exp2(arr)))



array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])


In [8]:
arr2 = np.array(([1,10],[np.e,np.pi]))
print(repr(np.log(arr2)))

print(repr(np.log10(arr2)))

array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [10]:
# raiseing to the power with any base np.power  first argument is base, second is the power

arr = np.array([[1, 2], [3, 4]])
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

# math routines
# https://numpy.org/doc/stable/reference/routines.math.html

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


In [12]:
# 3. Matrix Multiplication

# dot product 1 d array
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])

print(np.matmul(arr1,arr2)) # 1 * -3 + 2*0 + 3*10 = 27

27


In [13]:
arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in a ValueError: If we uncomment line 10 and run again.
#print(repr(np.matmul(arr3, arr3)))

array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])
