In [1]:
# Random
# Generate numbers and arrays from different random distributions.

# 1. Random integers
# 2. Utility functions
# 3. Distributions
# 4. Custom sampling


import numpy as np

In [19]:
# 1. Random integers

print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=0, size = (2,2))
print(repr(random_arr))

0
0
5
array([[-2, -2],
       [-1, -2]])


In [21]:
# 2. Utility functions // for reproducability
# seed and shuffle 

np.random.seed(1)

print(np.random.randint(10))

random_arr = np.random.randint(low = 3, high = 100, size = (2,2))
print(repr(random_arr))

# new seed
np.random.seed(2)

print(np.random.randint(10))

random_arr = np.random.randint(low = 3, high = 100, size = (2,2))
print(repr(random_arr))

np.random.seed(1)

print(np.random.randint(10))

random_arr = np.random.randint(low = 3, high = 100, size = (2,2))
print(repr(random_arr))




5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [29]:
# np.random.shuffle (happens in place) for multi-dimension -> only first dimension or rows effectively

vec = np.array([1,2,3,4,5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([1, 5, 3, 4, 2])
array([4, 2, 1, 5, 3])
array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])


In [30]:
# 3. Distributions (uniform,normal...)
# https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html
# you can set up loc = mean, scale = standard deviation 

print(np.random.uniform())
print(np.random.normal())

0.2936141483736795
-0.691660751725309


In [32]:
print(np.random.uniform(low = -1.5, high = 2.2))

print(repr(np.random.uniform(size = 3)))

print(repr(np.random.uniform(low=-3.4,high=5.9,size = (2,2))))

1.011691471877597
array([0.21162812, 0.26554666, 0.49157316])
array([[-2.90372833,  1.93929373],
       [-2.03542425,  2.08054149]])


In [34]:
# Normal
print(np.random.normal(loc=1.5,scale=3.5))

print(repr(np.random.normal(loc=-2.4, scale = 4.0,size = (2,2))))

0.11136265600407924
array([[-4.83994102, -1.17435048],
       [ 4.36730451, -5.39181497]])


In [35]:
# 4. Custom sampling

colors = ["red","blue","green"]

print(np.random.choice(colors))

print(repr(np.random.choice(colors, size = 2)))


red
array(['red', 'blue'], dtype='<U5')


In [40]:
# or like super fintuned
print(repr(np.random.choice(colors,size = (100), p = [0.8,0.19,0.01])))
# p set up probability red = 0.8, blue = 0.19, green = 0.01, by default probabilities are equal

array(['red', 'red', 'red', 'red', 'red', 'blue', 'red', 'red', 'red',
       'red', 'red', 'red', 'red', 'red', 'blue', 'red', 'red', 'red',
       'red', 'red', 'red', 'red', 'red', 'red', 'red', 'red', 'blue',
       'red', 'blue', 'red', 'blue', 'blue', 'red', 'blue', 'red', 'red',
       'red', 'red', 'red', 'red', 'red', 'red', 'red', 'blue', 'red',
       'red', 'red', 'red', 'red', 'red', 'blue', 'red', 'red', 'red',
       'red', 'red', 'red', 'red', 'red', 'blue', 'blue', 'red', 'red',
       'red', 'blue', 'red', 'red', 'red', 'red', 'red', 'red', 'red',
       'red', 'red', 'red', 'red', 'blue', 'blue', 'blue', 'red', 'red',
       'red', 'blue', 'red', 'red', 'red', 'red', 'red', 'red', 'red',
       'red', 'green', 'red', 'red', 'red', 'red', 'red', 'red', 'red',
       'red'], dtype='<U5')
