In [1]:
# Indexing

# 1. Array accessing
# 2. Slicing
# 3. Argmin and argmax



In [3]:
import numpy as np

#1. Array accessing
arr = np.arange(6)
print(arr[0])
print(arr[4])
print(arr)

0
4
[0 1 2 3 4 5]


In [4]:
# subarray
arr = np.array([[6,3],[0,2]])
print(repr(arr[1]))

array([0, 2])


In [5]:
# 2. Slicing
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [6]:
# multi-dimensional array
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(repr(matrix[:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


In [7]:
print(repr(matrix[1:]))

array([[4, 5, 6],
       [7, 8, 9]])


In [8]:
print(repr(matrix[:,-1])) # last column

array([3, 6, 9])


In [9]:
print(repr(matrix[:,1:])) # last two columns

array([[2, 3],
       [5, 6],
       [8, 9]])


In [17]:
print(repr(matrix[0:,1:]))

array([[2, 3],
       [5, 6],
       [8, 9]])


In [19]:
print(repr(matrix[0:1:,1:]))

array([[2, 3]])


In [22]:
# Argmin and argmax

# by default assumption is matrix get flattened
arr = np.arange(9)
print(arr)
print(np.argmin(arr))
print(np.argmax(arr))

[0 1 2 3 4 5 6 7 8]
0
8


In [26]:
arr = np.arange(9)
arr.resize((3,3))
print(arr)
print(np.argmin(arr))
print(np.argmax(arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
8


In [29]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-10, 9, 1]])
print(repr(np.argmin(arr, axis=0))) # index of the minimum row element for each column -10,-1,-6
print(repr(np.argmin(arr, axis=1))) # index of the minimum column element for each row  -3,-6,-10


array([2, 0, 1])
array([2, 2, 0])
