In [1]:
# Part 1 Statistics

# 1. Analysis
# 2. Statistical metrics

import numpy as np

In [3]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

print(arr.min()) # don't confuse with np.argmin and arg.max, they find index
print(arr.max())

-60
72


In [5]:
print(arr.min(axis=0)) # by column
print(arr.max(axis=1)) # by row

[ -3  -2 -60]
[72  3  4]


In [10]:
print(np.mean(arr)) # mean 
print(np.var(arr)) # variance
print(np.median(arr)) # median assumes flattened array
print(np.mean(arr,axis=0)) # by column

# https://numpy.org/doc/stable/reference/routines.statistics.html

2.0
977.3333333333334
1.0
[ -0.66666667  24.33333333 -17.66666667]


In [11]:
# Part 2 Aggregation

# 1. Summation
# 2. Concatenation



In [13]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])


print(np.sum(arr))
print(np.sum(arr, axis = 0)) # by col
print(np.sum(arr,axis= 1)) # by row

18
[ -2  73 -53]
[ 75 -56  -1]


In [14]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(repr(np.cumsum(arr))) # cumulutative sum
print(repr(np.cumsum(arr, axis=0))) # by col
print(repr(np.cumsum(arr, axis=1))) # by row

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


In [18]:
# concatenation of two arrays
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])

print(repr(np.concatenate([arr1,arr2]))) # by default axis = 0 or vertically

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])


In [19]:
print(repr(np.concatenate([arr1,arr2],axis= 1))) #  horizontally 

array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
