In [1]:

# 1. Standard dat format : due to ubiquitness of ranges like 0-10, 1500-3000, 5000-100000

# Numeric mesurements doesn't make much more sense, so the most common technique is to standardize data

# Formula -> for each (x - mean(x))/standard deviation(x) = z value <- standardized data value



In [2]:
# 2. For most scikit-learn functions, input needs to be in the form of NumPy array

# each rows is an observation, each column represent a feature, classic 2d matrix


In [3]:
import numpy as np
from sklearn.preprocessing import scale

# Define new dummy data
individual_data = np.array([
    [170, 70, 30],
    [180, 80, 35],
    [160, 60, 25],
    [175, 75, 32],
    [165, 65, 28]
])

In [6]:
col_standardized = scale(individual_data)
print(col_standardized)

[[ 0.          0.          0.        ]
 [ 1.41421356  1.41421356  1.46805055]
 [-1.41421356 -1.41421356 -1.46805055]
 [ 0.70710678  0.70710678  0.58722022]
 [-0.70710678 -0.70710678 -0.58722022]]


In [7]:
col_means = col_standardized.mean(axis = 0).round(decimals = 3)
print(col_means)

[0. 0. 0.]


In [8]:
col_stds = col_standardized.std(axis=0)
print(col_stds)

[1. 1. 1.]


In [9]:
# so when you average is 0 and standard deviation is 1, you achieved data standartization based on z 
# this technique is called Z-score normalization
