In [5]:
# with Z-scoring and MinMax, you have a problem, where outliers can dramatically affect your normalization

# so another approach is to subtract median

import numpy as np
from sklearn.preprocessing import RobustScaler # fit_transform, fit, transform

In [6]:
data = np.array([
    [170, 70, 30],
    [180, 80, 35],
    [160, 60, 25],
    [175, 75, 32],
    [165, 65, 28]
])

In [7]:
robust_scaler = RobustScaler()
transformed = robust_scaler.fit_transform(data)
print(transformed)

[[ 0.    0.    0.  ]
 [ 1.    1.    1.25]
 [-1.   -1.   -1.25]
 [ 0.5   0.5   0.5 ]
 [-0.5  -0.5  -0.5 ]]


In [8]:
# L2 Normalization

# sometimes we need to apply normalization by row
# L2Norm = sqrt(sum(x*x)) for x in row
# for value in row:
    # value/L2Norm


# Normalizer does that job, applyied by row !

from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
transformed = normalizer.fit_transform(data)

print(transformed)


[[0.91260782 0.37577969 0.16104844]
 [0.89971888 0.39987506 0.17494534]
 [0.92646658 0.34742497 0.1447604 ]
 [0.90643162 0.3884707  0.1657475 ]
 [0.91902398 0.36203975 0.15595558]]
