In [1]:
# 1. When data have a few missing fields.
# Common strategy is to fill it with some other values
# which may be make sense, common values are:

# Mean, Median, Most Frequent, Constant
import numpy as np

# Create the array with NaN values
array = np.array([
    [1., 2., np.nan, 2.],
    [5., np.nan, 1., 2.],
    [4., np.nan, 3., np.nan],
    [5., 6., 8., 1.],
    [np.nan, 7., np.nan, 0.]
])

print(array)

[[ 1.  2. nan  2.]
 [ 5. nan  1.  2.]
 [ 4. nan  3. nan]
 [ 5.  6.  8.  1.]
 [nan  7. nan  0.]]


In [2]:
# by default column means

from sklearn.impute import SimpleImputer 
imp_mean = SimpleImputer()
transformed = imp_mean.fit_transform(array)
print(transformed)

[[1.   2.   4.   2.  ]
 [5.   5.   1.   2.  ]
 [4.   5.   3.   1.25]
 [5.   6.   8.   1.  ]
 [3.75 7.   4.   0.  ]]


In [3]:
# you may also specify a specific strategy for filling values

imp_median = SimpleImputer(strategy="median")
transformed = imp_median.fit_transform(array)

print(transformed)

[[1.  2.  3.  2. ]
 [5.  6.  1.  2. ]
 [4.  6.  3.  1.5]
 [5.  6.  8.  1. ]
 [4.5 7.  3.  0. ]]


In [4]:
imp_frequent = SimpleImputer(strategy="most_frequent")
transformed = imp_frequent.fit_transform(array)
print(transformed)

[[1. 2. 1. 2.]
 [5. 2. 1. 2.]
 [4. 2. 3. 2.]
 [5. 6. 8. 1.]
 [5. 7. 1. 0.]]


In [5]:
imp_constant = SimpleImputer(strategy='constant',fill_value=-1)
transformed = imp_constant.fit_transform(array)
print(transformed)

[[ 1.  2. -1.  2.]
 [ 5. -1.  1.  2.]
 [ 4. -1.  3. -1.]
 [ 5.  6.  8.  1.]
 [-1.  7. -1.  0.]]
